use_frameworks!

platform :ios, '9.0'

target 'JanstiLib_Example' do
  pod 'JanstiLib', :path => '../'

  target 'JanstiLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
